[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.1
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  bblanchon/ArduinoJson @ ^7.4.2
